import type { Card } from "@inuyasha/shared";

export const CARD_POOL: Card[] = [
  {
    id: "step_forward",
    name: "전진",
    type: "move",
    energyCost: 1,
    energyGain: 0,
    damage: 0,
    defenseValue: 0,
    summary: "거리 압박을 위한 기본 이동 카드",
  },
  {
    id: "step_back",
    name: "후퇴",
    type: "move",
    energyCost: 1,
    energyGain: 0,
    damage: 0,
    defenseValue: 0,
    summary: "안전 거리 확보를 위한 이동 카드",
  },
  {
    id: "quick_slash",
    name: "속공 베기",
    type: "attack",
    energyCost: 2,
    energyGain: 0,
    damage: 4,
    defenseValue: 0,
    summary: "가벼운 기본 공격",
  },
  {
    id: "heavy_slash",
    name: "강공 베기",
    type: "attack",
    energyCost: 3,
    energyGain: 0,
    damage: 7,
    defenseValue: 0,
    summary: "큰 피해를 노리는 무거운 공격",
  },
  {
    id: "guard",
    name: "방어",
    type: "defense",
    energyCost: 1,
    energyGain: 0,
    damage: 0,
    defenseValue: 5,
    summary: "받는 피해를 줄이는 기본 방어",
  },
  {
    id: "barrier",
    name: "결계",
    type: "defense",
    energyCost: 2,
    energyGain: 0,
    damage: 0,
    defenseValue: 8,
    summary: "더 강한 방어를 제공하는 카드",
  },
  {
    id: "focus",
    name: "집중",
    type: "energy_recover",
    energyCost: 0,
    energyGain: 2,
    damage: 0,
    defenseValue: 0,
    summary: "다음 교전을 위해 기력을 회복한다",
  },
  {
    id: "meditate",
    name: "명상",
    type: "energy_recover",
    energyCost: 0,
    energyGain: 3,
    damage: 0,
    defenseValue: 0,
    summary: "큰 폭의 에너지 회복을 노린다",
  },
  {
    id: "first_aid",
    name: "응급 처치",
    type: "hp_recover",
    energyCost: 1,
    energyGain: 0,
    damage: 0,
    defenseValue: 0,
    summary: "작은 체력 회복 카드",
  },
  {
    id: "burst",
    name: "폭발 일격",
    type: "attack",
    energyCost: 4,
    energyGain: 0,
    damage: 9,
    defenseValue: 0,
    summary: "높은 비용의 강력한 공격",
  },
];
